### ISSUE TITLE
iot Charts

### ISSUE THREAD

**Issue by jlmyra** [MikeTeachman/gadgets-iotcharts#1]
I've have been using your (amazing) iotcharts gadget for about 4 months. All of a sudden the google chart does not display. I have not changed anything recently other than relocating the page on the site. 
https://sites.google.com/site/myraclegarden/home
Any ideas? Thanks!

**Comment by miketeachman** [comment]
Hi,

thanks for letting me know the charts are broken !  I took a look and found
that spin.js is causing a security error in google sites. I'm not sure why
now?

I was able to comment out the spinner library import, and the spinner
Javascript inside the jquery call.  Then it worked.  That should work for
you.  Is this enough description to work with?  If not, I can send you the
code to change.

Mike

**Comment by jlmyra** [comment]
Hi Mike!
Thanks for solving the issue for me. I would not have figured this out on
my own. Your code has been very useful to me-see below. I have fixed the
first of two websites that use your code. I am not an experienced 'coder'
but I do have enough patience to cobble together code that others have
shared to make my gadgets work. I appreciate you sharing your time, effort
and wisdom with me.

We are using your gadget to help us remotely monitor greenhouse conditions
via Arduino and Thingspeak. Our community garden club grew 1400 tomato
plants for our annual plant sale raising about $4700 that we will reinvest
in the community. The hardware and website featuring your gadget allowed us
to look at the temperature and rh continuously giving us insight into how
we could optimize the heating and cooling in the greenhouse. The greenhouse
website is https://goo.gl/H3cSRa although we have stopped running the
arduino for the summer. I have an additional setup in my basement where I
raise plants for my own vegetable garden https://goo.gl/Htb1da

Again, Thanks very much!

Jim Myracle

**Comment by miketeachman** [comment]
Hi Jim,

I just checked out the websites.  Very cool !  A community garden is a great use for Google Sites.  You figured out a lot.  It's not obvious how to configure these gadgets.  Leaving the right configuration panel in place makes it interactive for site users, to configure the chart how they want to see it.

I'm starting to work on part II of the IoT charts Instructable.  I hope to have that done in about a month from now.  But, with summer coming I don't get as much project time as I'd like, so it might end up being 2 months !  Part II will have more google gadgets that can be linked to ThingSpeak and Sparkfun Data.  And, a site template that should make it fast to build a sensor site.

Can I ask a favor?   Would you be able to take a minute to describe the workflow you used to install and configure the gadget on the google sites you built?  I curious to learn about any challenges you faced.  That will help me with part II, to best describe a workflow that is easy to follow.

A couple of final questions:  what monitor resolution do you use? (e.g.  1280x800)  and, do you ever want to see the charts using a mobile device? (the gadget is presently not optimized for mobile devices).

thanks!

Mike
  ----- Original Message -----

**Comment by jlmyra** [comment]
Hi!
I'll answer your last question first. The screen resolution on my Mac is
1440 x 900. Mobile phone use is very important. I usually want to look at
the data when I am at the greenhouse but I rarely have my laptop but I
always have my iPhone. As you know the right side of the graph is chopped
off and I am unable to see the settings pane to change the time series if I
want to for some reason. So, yes mobile access would be very useful to me.
I have thought about playing with the gadget code to see if I could adjust
it for the phone but I have never found the time. Google sites has a mobile
display setting as well but there appears to be a whole learning curve(for
me) associated with that.

As for the workflow question, I will think about my experience and send you
my thoughts in a few days. I am out of town on business right now.

Thanks again.
Jim

**Comment by miketeachman** [comment]
Hi Jim,

Thanks for sharing your insights on mobile usage.  I'm going to try to
learn how to make future gadgets work better on mobile devices.  There are
gadget design best practices to make a gadget "gracefully adapt" to smaller
screens.  It would be a good ambition to implement these practices on
future gadgets.

Mike

**Comment by jlmyra** [comment]
Hi.
Sorry for the delay. I retraced my steps and recall that once I found your
Github entry and read your instructions (thoroughly) for installing the
gadget I was able to get the charts running. The challenge for me was that
I was in uncharted waters--I was unfamiliar with GoogleSites which are not
at all intuitive and my pathway for even attempting to solve my problem
this way was tortuous.
As I gained confidence with writing arduino sketches I added an SD card to
record the data, then ethernet and a web server thinking I could access the
data remotely and view it in Excel. This required hacking an old router
with ddWrt operating in a client bridge mode-- but that's a whole other
story). The problem is that the sketch generates so much data that it
overwhelmed Excel. In searching for alternatives to Excel I came across
Thingspeak which was one of the easiest elements that I added to my sketch.
It was very easy to get up and running. I was very disappointed with the
graphing capability offered so I started looking for alternative IoT sites
to Thingspeak. There are plenty of them out there but I could not get any
of them to work as they are much more complicated and the the documentation
is very poor. So, I decided to get some help. I went to a hackerspace in
Manhattan that offers Arduino Tuesdays
http://www.meetup.com/fat-cat-fab-lab/events/231176736/ thinking I would
find someone that could show me how to get one or more of the Thingspeak
alternatives to work. The session was attended largely by coders who wanted
to learn more about hardware. Unfortunately no one knew anything about what
I was attempting to do. But, as the session was ending a guy sitting next
to me- a coder at Autodesk- said "it could be you are approaching the
problem the wrong way- consider creating a website and use Google charts to
graph the Thingspeak dataset." This was not the answer I wanted to hear- I
really didn't have the time to create a website and figure out how to use
Google Charts. But, the next day I googled free website hosting and found
GoogleSites and got a site up and running. Then I explored Google Charts
and was completely overwhelmed. I started googling a lot of different
things related to arduino, google charts, etc. and came across your github
entry. After a couple of attempts (finally following your instructions
thoroughly) I got the gadget to work. I studied your (amazing) code and
figured out how to get the Google Gauges
https://sites.google.com/site/myraclegarden/gauges to work on my site too.
I wish your Instructable had been available at the time. I'm sure it would
have saved me a lot of time. I'm really proud of what I built and I owe a
lot of unknowing contributors like yourself my very deep gratitude for your
wisdom and desire to share. Again, a very heartfelt Thank-you for sharing
your code and helping me along my learning journey.

Best,
Jim

**Comment by miketeachman** [comment]
Hi Jim,

That is a great story !  I can totally relate to struggles, dead-ends, and
then the incredible moments when something actually works.    You built a
great site.  I know it's not easy with Google sites to get your graph page
looking so clean, with no weird borders, and gadgets landing where you want
them.  That is excellent you adapted the code to work with gauges.    I'd
like to add gauges to the next release of the IoT charts.  I got a gauge
mostly working a couple of nights ago, but it was a real battle for me to
adapt my code from the line chart to a single point.  I'm "code by google
example" Javascript programmer so these things are often trial and error
efforts !  I'm a lot more comfortable with C code on embedded devices.  I'm
still getting used to ajax concepts with nested callbacks.

I've pretty much decided that the next tutorial will be "mobile first" --
trying to show how to built gadget-charts in google sites that look great
on our phones.  I think configuration of the google site will still need a
laptop or desktop computer, but the viewing will be targeted at phones.
Lots more googling, stack exchange, and digging into the google
visualization api docs.

It's quite an amazing time we live in.  There is so much information that
people have shared.  Part of my motivation for posting my work is to give
back in whatever way it can.

All the best,

Mike

**Comment by jlmyra** [comment]
Hi!
Attached is my code for the google gauge gadget. Probably nothing here that
you haven't figured out but just in case...

Also, here is a link to a JSFiddle page where you can play with the dial
colors and other settings without having to make a gadget each time to see
the effect. https://jsfiddle.net/jlmyra/z57d6rm1/#&togetherjs=H0aQ4wlOJL

I too am definitely a learn to code by example. If not for all the shared
examples I'd have nothing.

As a footnote, I learned to code in Basic and Fortran from my Dad and in
college, yes back in the punch card days. It was just at the time that
'time-sharing' emerged where one could interact with remote computers
through terminals, mostly Teletypes. I got a job as a summer intern in 1972
at General Electric's Information Services Business Division. They kept me
on during the winter months as I attended college. They installed a
separate phone line, a Model 33 Teletype https://goo.gl/t1lX9j and
initially a 15 character per second acoustic coupler phone modem. You can't
imagine my excitement when I was upgraded to a 30 cps modem! Woo-hoo!
And, here I am ~45 years later playing with an Arduino...

Thanks again,
Jim
